name: Deploy Frontend
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: Name of the application
        required: true
        type: string
        default: gzabarte
      environment:
        description: Deployment
        required: true
        type: choice
        default: dev
        options:
          - dev
          - stg
          - prd
permissions:
  id-token: write
  contents: read
jobs:
  terraform-bucket-creation:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github
          aws-region: us-west-2
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github
          aws-region: us-west-2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5
      - name: Install Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: 0.80.4
      - name: Create Frontend bucket
        run: ./.github/scripts/create_bucket.sh
        env:
          APP_NAME: ${{ inputs.app_name }}
          AWS_IAM_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github
          ENVIRONMENT: ${{ inputs.environment }}
          BUCKET: ${{ inputs.environment }}-${{ inputs.app_name }}-frontend
      - name: Create Terraform bucket
        run: ./.github/scripts/create_bucket.sh
        env:
          APP_NAME: ${{ inputs.app_name }}
          AWS_IAM_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github
          ENVIRONMENT: ${{ inputs.environment }}
          BUCKET: ${{ inputs.environment }}-${{ inputs.app_name }}-tf
      - name: Frontend deployment
        run: ./.github/scripts/deploy_frontend.sh
        env:
          APP_NAME: ${{ inputs.app_name }}
          ENVIRONMENT: ${{ inputs.environment }}
          TF_BUCKET: ${{ inputs.environment }}-${{ inputs.app_name }}-frontend
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Build Frontend
        working-directory: source/frontend
        run: |
          npm ci
          npm run build
      - name: Upload Frontend to S3
        working-directory: source/frontend
        run: |
          aws s3 sync ./dist "s3://${{ inputs.environment }}-${{ inputs.app_name }}-frontend" --delete
        env:
          AWS_DEFAULT_REGION: us-west-2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5
      - name: Install Terragrunt
        uses: autero1/action-terragrunt@v3
        with:
          terragrunt-version: 0.80.4
      - name: Cloudfront invalidation
        working-directory: source/deployment/cloudfront
        run: |
          terragrunt apply --all --non-interactive -no-color
          terragrunt output -raw cloudfront_distribution_id
          CLOUDFRONT_DISTRIBUTION_ID=$(terragrunt output -raw cloudfront_distribution_id)
          aws cloudfront create-invalidation --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" --paths "/*"
        env:
          APP_NAME: gzabarte
          APP_VERSION: ${{ needs.prepare.outputs.version }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          ENVIRONMENT: ${{ inputs.environment }}
          TF_BUCKET: ${{ inputs.environment }}-{{ inputs.app_name }}$-tf
